name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: 'stable'

      - name: Build
        run: |
          cd lab3/impl
          go mod tidy
          go build -v ./...

      - name: Lint
        uses: golangci/golangci-lint-action@v4
        with:
          version: latest
        run: |
          cd lab3/impl
          golangci-lint run

      - name: Fuzzing test
        run: |
          cd lab3/impl
          go list ./... | grep -vE '(test|scripts|cmd|mock|gen)' | xargs -I{} go test -fuzz=Fuzz -fuzztime=10s {}

      - name: Test
        run: |
          cd lab3/impl
          go test -v -race -coverprofile=./cover.out -covermode=atomic -coverpkg=$(go list ./... | grep -vE '(test|scripts|cmd|mock|gen)' | tr '\n' ',') ./...

